# Generated by Django 4.0.6 on 2022-08-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaknounApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arango_host', models.CharField(blank=True, max_length=200, null=True)),
                ('arango_username', models.CharField(blank=True, max_length=200, null=True)),
                ('arango_password', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='datafield',
            name='data_type',
            field=models.CharField(choices=[('String', 'نص'), ('Number', 'رقم'), ('Date', 'تاريخ'), ('Bool', 'حقيقة')], default=False, max_length=13),
        ),
    ]
