# Generated by Django 4.0.6 on 2022-08-16 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaknounApp', '0002_settings_alter_datafield_data_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='arango_host',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='settings',
            old_name='arango_password',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='arango_username',
        ),
    ]
