# Generated by Django 4.0.6 on 2022-08-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaknounApp', '0003_rename_arango_host_settings_key_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='Setting',
        ),
    ]
