# Generated by Django 4.0.6 on 2022-08-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaknounApp', '0004_rename_settings_setting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='id',
        ),
        migrations.AlterField(
            model_name='setting',
            name='key',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
