# Generated by Django 4.0.4 on 2022-06-11 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=70)),
                ('arabic_name', models.CharField(max_length=70)),
                ('icon_class', models.CharField(blank=True, max_length=70, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=70)),
                ('arabic_name', models.CharField(max_length=70)),
                ('indexed', models.BooleanField(default=True)),
                ('date_type', models.CharField(choices=[('String', 'نص'), ('Number', 'رقم'), ('Date', 'تاريخ'), ('Bool', 'حقيقة'), ('Array', 'لائحة'), ('Object', 'شيء')], max_length=6)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=70)),
                ('arabic_name', models.CharField(max_length=70)),
                ('compressed', models.BooleanField(default=False)),
                ('data_fields', models.ManyToManyField(to='datacoreapp.datafield')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=70)),
                ('arabic_name', models.CharField(max_length=70)),
                ('from_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromBank', to='datacoreapp.bank')),
                ('to_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toBank', to='datacoreapp.bank')),
            ],
        ),
    ]
