# Generated by Django 4.0.4 on 2022-06-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacoreapp', '0001_createdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='data_type',
            field=models.CharField(choices=[('String', 'نص'), ('Number', 'رقم'), ('Date', 'تاريخ'), ('Bool', 'حقيقة'), ('Array', 'لائحة'), ('Object', 'شيء')], default=False, max_length=6),
        ),
    ]
