# Generated by Django 4.0.5 on 2022-06-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacoreapp', '0002_rename_data_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='replication_factor',
            field=models.IntegerField(default=1),
        ),
    ]
