# Generated by Django 4.0.5 on 2022-06-21 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datacoreapp', '0005_fix_database_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='database',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='bank_database', to='datacoreapp.database'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relation',
            name='database',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='relation_database', to='datacoreapp.database'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='view',
            name='database',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='view_database', to='datacoreapp.database'),
            preserve_default=False,
        ),
    ]
