# Generated by Django 4.0.5 on 2022-06-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacoreapp', '0006_fix_database_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
