# Generated by Django 4.0.5 on 2022-06-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacoreapp', '0007_add_custom_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='english_name',
            field=models.CharField(default='admin', max_length=70),
            preserve_default=False,
        ),
    ]
