# Generated by Django 4.0.5 on 2022-06-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datacoreapp', '0008_add_user_english_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='arabic_name',
            field=models.CharField(default='المدير', max_length=70),
            preserve_default=False,
        ),
    ]
