# Generated by Django 4.0.5 on 2022-06-22 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datacoreapp', '0009_add_user_arabic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='host',
        ),
        migrations.RemoveField(
            model_name='database',
            name='password',
        ),
        migrations.RemoveField(
            model_name='database',
            name='username',
        ),
    ]
